name: Testing the Test-files of CA4
run-name: ${{ github.actor }} - ${{ github.event_name }}

on:
  push:
    paths:
      - 'CA1/**'
      - '.github/workflows/CA4tests.yml'


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '19'

      - run: |
          cd CA1
          mvn -B package --file pom.xml
